site_name: Magnus的小站
site_url: https://github.com/Magnus031/NoteBooks
repo_name: Magnus031/NoteBooks
repo_url : https://github.com/Magnus031/NoteBooks 

nav:
  - 主页 : index.md
  - 关于我 : about.md
  - 教程 : 
    - JS/TS : Tutorial/JS&TS/TS.md
    - Java :
      - Objects and classes : Tutorial/Java/Java4.md
      - Inheritance : Tutorial/Java/Java5.md
      - Interface : Tutorial/Java/Java6.md
  - 数据结构与算法: 
    - DP : LeetCode/DP/DP.md
    - Tree : LeetCode/Tree/BinaryTree.md
theme: 
  name : material

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
      